<?php $this->layout('layout::default', ['title' => 'Anderson Luciano - Web Developer']) ?>

<div class="row">
    <div class="col s4">
        <img src="/assets/images/profile.JPG" alt="" class="circle responsive-img profile-pic z-depth-4">
        <h1 class="name">Anderson Luciano</h1>
        <h2 class="function">Web Developer</h2>
        <p class="description">PHP programmer <i class="fa fa-code-fork"></i>, coffee lover <i class="fa fa-coffee"></i>, and Bruna's husband <i class="fa fa-heart"></i></p>
    </div>
    <div class="col s8">
        <div class="row">
            <div class="parallax-container parallax-container-bigger">
                <div class="parallax"><img src="/assets/images/deep-space.jpg"></div>
            </div>
            <div class="section white">
                <div class="row">
                    <div class="col s12 m12 center-align">
                        <a href="https://www.thedevelopersconference.com.br" target="_blank" title=" The Developer's Conference 2018, um evento organizado pela Globalcode" style="text-decoration: none;"><img src="https://s3-sa-east-1.amazonaws.com/thedevconf/2018/img/divulgacao/saopaulo/banner-TDC2018-sampa-468x60.png" style="border:none;" alt="Evento TDC2018" /></a>
                        <p>Estarei presente e <b>palestrando</b> \o/ <br>
                        Dia <b>21/07</b> trilha <b>Arquitetura PHP</b> com o tema <b>PHP Middlewares, o que são? Onde vivem? O que fazem?</b><br>Nos vemos por lá!</p>
                    </div>
                </div>
                <div class="row">
                    <h2 class="header">Backend Skills</h2>
                    <div class="row">
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/ZendFramework-logo.png">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-cogs"></i> <b>Zend Framework</b></p>
                                        <small>(Since first version until Zend Expressive) Okay... maybe I'm a Zend Frame fan.</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://framework.zend.com" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/doctrine.png">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-cogs"></i> <b>Doctrine ORM</b></p>
                                        <small>One of the best ORM's</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://www.doctrine-project.org" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/node.png">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-cogs"></i> <b>NodeJs</b></p>
                                        <small>Socket.io</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://nodejs.org/en/" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                    <div class="row">
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/tux.jpg">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-linux"></i> <b>Linux Lover</b></p>
                                        <small>Ubuntu, Slackware, Debian, Fedora</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://www.ubuntu.com" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/webservices.jpg">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-comments"></i> <b>Webservice Maker</b></p>
                                        <small>REST, SOAP</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://en.wikipedia.org/wiki/Web_service" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="parallax-container">
                <div class="parallax"><img src="/assets/images/milky-way.jpg"></div>
            </div>
            <div class="section white">
                <div class="row">

                    <h2 class="header">Frontend Skills</h2>

                    <div class="row">
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/jquery.png">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-hand-o-right"></i> <b>Javascript</b></p>
                                        <small>Jquery, Plugin Maker, Web Componets...</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://jquery.com" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/htmlcss.png">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-css3"></i> <b>CSS</b></p>
                                        <small>Boostrap, Semantic UI, Materializecss</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://getbootstrap.com" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="parallax-container">
                <div class="parallax"><img src="/assets/images/moon.jpg"></div>
            </div>
            <div class="section white">
                <div class="row">

                    <h2 class="header">Database knowledge</h2>

                    <div class="row">
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/postgresql-logo.png">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-database"></i> <b>Databases SQL</b></p>
                                        <small>PostgreSQL (<a href="https://www.dextraining.com.br" target="_blank">Dextra Training Course</a>), Mysql, Oracle</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://www.postgresql.org" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/mongo.png">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-database"></i> <b>Databases NOSQL</b></p>
                                        <small>MongoDb , Cassandra, Redis, DynamoDb, CouchDb</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://en.wikipedia.org/wiki/NoSQL" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="parallax-container">
                <div class="parallax"><img src="/assets/images/sky-clouds.jpg"></div>
            </div>
            <div class="section white">
                <div class="row">

                    <h2 class="header">Infrastructure</h2>
                    <div class="row">
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/aws.png">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-amazon"></i> <b>AWS</b></p>
                                        <small>User since 2014: EC2 Instances , DynamoDb, RDS, S3</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://aws.amazon.com" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/digocean.png">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-server"></i> <b>Digital Ocean</b></p>
                                        <small>Client since 2013</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://digitalocean.com" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="parallax-container">
                <div class="parallax"><img src="/assets/images/sky-orange.jpg"></div>
            </div>
            <div class="section white">
                <div class="row">
                    <h2 class="header">Miscellaneous</h2>

                    <div class="row">
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/OSM_p01.png">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-map"></i> <b>OpenStreetMaps contributor</b></p>
                                        <small>Self Host Maps Server</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://www.openstreetmap.org" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/osrm_logo.svg">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-road"></i> <b>OSRM Project</b></p>
                                        <small>Routing Machine</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://project-osrm.org" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/postgis-logo.png">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-map-marker"></i> <b>PostGis</b></p>
                                        <small>PostgreSQL support for geographic objects</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://postgis.net" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                    <div class="row">
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/telegram-logo-11.png">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-telegram"></i> <b>Telegram Bots</b></p>
                                        <small>for integrations or services</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://telegram.org" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/Git-Logo-2Color.png">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-code-fork"></i> <b>Git</b></p>
                                        <small>Github, Bitbucket, etc, etc...</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://git-scm.com" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col s12 m4">
                            <div class="card hoverable">
                                <div class="card-image">
                                    <img class="materialboxed" src="/assets/images/technologies/android-logo_0.jpg">
                                </div>
                                <div class="card-stacked">
                                    <div class="card-content">
                                        <p><i class="fa fa-android"></i> <b>Android</b></p>
                                        <small>Java</small>
                                    </div>
                                    <div class="card-action">
                                        <a href="https://www.android.com" target="_blank">Learn more about</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">

                    <h2 class="header">Let's talk!</h2>

                    <div class="row center" id="social-media">
                        <div class="col s4">
                            <h6 class=""><a class="grey-text" target="_blank" href="https://github.com/rockeinstein"><i class="fa fa-github"></i> @Rockeinstein</a></h6>
                        </div>
                        <div class="col s4">
                            <h6><a class="grey-text" target="_blank" href="https://facebook.com/anderson.end"><i class="fa fa-facebook"></i> Anderson Luciano</a></h6>
                        </div>
                        <div class="col s4">
                            <h6><a class="grey-text" href="mailto:andersonluciano.dev@gmail.com"><i class="fa fa-google"></i> andersonluciano.dev@gmail.com</a></h6>
                        </div>
                    </div>

                    <form id="form-contact" action="#form-contact" method="post" class="col s12">
                        <div class="row">
                            <div class="input-field col s12">
                                <input placeholder="Mr Anderson!" id="name" name="name" type="text" class="validate" value="<?= array_key_exists("name", $params) ? $params['name'] : "" ?>">
                                <label for="name">You Name</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input placeholder="andersonluciano.dev@gmail.com" id="email" name="email" type="email" class="validate" value="<?= array_key_exists("email", $params) ? $params['email'] : "" ?>">
                                <label for="email">You Email</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <textarea id="message" name="message" class="materialize-textarea" placeholder="Feel free!"><?= array_key_exists("message", $params) ? $params['message'] : "" ?></textarea>
                                <label for="message">Your message</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s12">
                                <div class="g-recaptcha" data-sitekey="6LfwnA4UAAAAAFPCJyxKkdajKOImP1SB_UZgCrxE"></div>
                            </div>
                        </div>
                        <?php
                        if ($params['messageResponse'] != "") {
                            ?>
                            <div class="card-panel teal lighten-2"><?= $params['messageResponse'] ?></div>
                            <?php
                        }
                        if ($params['exception'] != "") {
                            ?>
                            <div class="card-panel red lighten-5"><?= $params['exception'] ?></div>
                            <?php
                        }
                        ?>
                        <div class="row">
                            <div class="col s12">
                                <button id="btn-submit" type="button" class="waves-effect waves-light btn  deep-orange lighten-1"><i class="fa fa-check"></i> Send</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="parallax-container parallax-container-bigger">
            <div class="parallax"><img src="/assets/images/me.jpg"></div>
        </div>
    </div>
</div>
<footer class="page-footer blue-grey lighten-5 text-darken-2">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="grey-text text-darken-3 my-name">Anderson Luciano</h5>
                <h6 class="grey-text text-darken-2 my-name">Web Developer</h6>
                <p class="grey-text">Thanks for your visit!</p>
            </div>
            <div class="col l6  s12">
                <h5 class="grey-text">Links</h5>
                <ul>
                    <li><a class="" href="https://github.com/rockeinstein"><i class="fa fa-github"></i> @Rockeinstein</a></li>
                    <li><a class="" href="https://facebook.com/anderson.end"><i class="fa fa-facebook"></i> @Anderson.End</a></li>
                    <li><a class="" href="mailto:andersonluciano.dev@gmail.com"><i class="fa fa-google"></i> andersonluciano.dev@gmail.com</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            <p class="grey-text text-darken-3 jesus">Jesus is the savior!</p>
<!--            Yess He is!                                                                                     -->
<!--            John 3:16-18                                                                                    -->
<!--            ------------                                                                                    -->
<!--            16 For God so loved the world, that he gave his only begotten Son,                              -->
<!--            that whosoever believeth in him should not perish, but have everlasting life.                   -->
<!--            17 For God sent not his Son into the world to condemn the world; but that                       -->
<!--            the world through him might be saved.                                                           -->
<!--                                  ---------------                                                           -->
<!--            18 He that believeth on him is not condemned: but he that believeth not is                      -->
<!--            condemned already, because he hath not believed in the name of the only begotten Son of God.    -->
<!--            --------------------------------------------------------------------------------------------    -->
<!--            Jesus is life, Jesus is salvation, come to Jesus!                                               -->
        </div>
    </div>
</footer>

<?php $this->start("javascript") ?>
<script>
    $(function () {
        $('.button-collapse').sideNav();
        $('.parallax').parallax();
        $('.materialboxed').materialbox();


        $("#btn-submit").click(function () {
            if ($("#name").val() == "") {
                Materialize.toast('Please tell me your name :)', 4000);
                $("#name").focus();
                return false;
            }
            if ($("#email").val() == "") {
                Materialize.toast('Please tell me your email :)', 4000);
                $("#email").focus();
                return false;
            }
            if ($("#message").val() == "") {
                Materialize.toast('OMG, you do not want to say anything? :O', 4000);
                $("#message").focus();
                return false;
            }

            $(this).parents("form").submit();
        });
    });
</script>

<script src="/assets/materialize/js/materialize.min.js"></script>
<?php $this->stop() ?>

<?php
$this->start("stylesheets")
?>
<style>
    .parallax-container {
        height: 100px;
    }

    .parallax-container-bigger {
        height: 350px;
    }

    .profile-pic {
        width: 247px;
        margin-left: 25%;
        margin-top: 10%;
    }

    .card-image {
        height: 119px;
        overflow: hidden;
    }

    .name {
        font-family: MyName;
        font-size: 52px;
        text-align: right;
    }

    .jesus {
        font-family: MyName;
    }

    .my-name {
        font-family: MyName;
    }

    .function {
        font-family: ProHandy;
        font-size: 56px;
        text-align: right;
    }

    .description {
        text-align: center;
    }

    .section > .row > .header {
        font-family: ProHandy;
    }

    #social-media > div:first-child {
        border-right: 1px solid #e2e2e2;
    }

    #social-media > div:last-child {
        border-left: 1px solid #e2e2e2;
    }

    #social-media :hover {
        color: #000 !important;
    }

</style>
<?php $this->stop() ?>
